#!/usr/bin/env bash

# Create a local apptainer sif image from a cvmfs based sandbox
# to list available images just look at
# ls -1l /cvmfs/alice.cern.ch/containers/fs/apptainer

ALICE_IMG_DIR="/cvmfs/alice.cern.ch/containers/fs/apptainer"
ALICE_IMG_NAME="x86_64/alma9-alice-20250311"

export SANDBOX_CVMFS="${ALICE_IMG_DIR}/${ALICE_IMG_NAME}"
export SANDBOX_DIR="./sandbox"
mkdir -p "${SANDBOX_DIR}"

export MY_UID="$(id -un)"
export MY_GID="$(id -gn)"
NAME="$(basename ${ALICE_IMG_NAME})"

[[ ! -d "${SANDBOX_CVMFS}" ]] && { echo "sandbox directory not available: ${SANDBOX_CVMFS}" ; exit 1; }
sudo cp -a "${SANDBOX_CVMFS}" "${SANDBOX_DIR}" && \
sudo chown -R ${MY_UID}:${MY_GID} "${SANDBOX_DIR}" && \
apptainer build --disable-cache --fix-perms "${NAME}.sif" "${SANDBOX_DIR}/${NAME}"

[[ -d "${SANDBOX_DIR}" ]] && rm -rf "${SANDBOX_DIR}"

