#!/usr/bin/env bash

mkdir -p BUILD INSTALL
rm -rf BUILD/*

export BUILD_TAG="latest-o2physics-o2"

export WORK_DIR="${ALIBUILD_WORK_DIR}" ALIBUILD_ARCH_PREFIX="$(aliBuild architecture)" DISABLE_GPU=1

source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/JAliEn-ROOT/${BUILD_TAG}/etc/profile.d/init.sh
source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/libjalienO2/${BUILD_TAG}/etc/profile.d/init.sh
#source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2/${BUILD_TAG}/etc/profile.d/init.sh
source ${WORK_DIR}/${ALIBUILD_ARCH_PREFIX}/O2Physics/${BUILD_TAG}/etc/profile.d/init.sh

env > compilation_env.txt

CMAKE_DEBUG_OPTS=""
[[ -n ${CMAKE_DO_TRACE} ]] && CMAKE_DEBUG_OPTS=" --debug-output --debug-find --trace --trace-expand --trace-format=human --trace-redirect=cmake_trace.log "

pushd BUILD
cmake3 -DCMAKE_INSTALL_PREFIX=../INSTALL -DBUILD_TEST_ROOT_MACROS=OFF ${CMAKE_DEBUG_OPTS} \
    -DLIBJALIENO2_INCLUDE_DIR=${LIBJALIENO2_ROOT}/include -DLIBJALIENO2_LIBPATH=${LIBJALIENO2_ROOT}/lib/libjalienO2.so \
    -DJALIEN_ROOT_INCLUDE_DIR=${JALIEN_ROOT_ROOT}/include -DJAliEnRoot_LIB=${JALIEN_ROOT_ROOT}/lib/libJAliEnROOT.so \
    ..

make -j4
make install

popd

