#!/usr/bin/env bash

# Load the environment for these ALICE modules
PKG_DATE_SHORT="202210"
PKG_DATE="20221030"

ALICE_PACKAGES="VO_ALICE@O2Physics::nightly-${PKG_DATE}-1,VO_ALICE@O2DPG::nightly-${PKG_DATE}-1"
eval $(/cvmfs/alice.cern.ch/bin/alienv printenv "${ALICE_PACKAGES}");

echo | o2-analysis-timestamp --aod-file @list.txt -b | o2-analysis-event-selection -b | o2-analysis-multiplicity-table -b | o2-analysis-centrality-table -b | o2-analysis-trackextension -b | o2-analysis-trackselection -b | o2-analysistutorial-flow-analysis -b

