#!/usr/bin/env bash

## Enable the environment
../enable

# Load the environment for these ALICE modules
echo | \
o2-analysis-timestamp --aod-file @list.txt -b | \
o2-analysis-event-selection -b | \
o2-analysis-multiplicity-table -b | \
o2-analysis-centrality-table -b | \
o2-analysis-trackextension -b | \
o2-analysis-trackselection -b | \
o2-analysistutorial-flow-analysis -b

